services:

##########################################
##
## napkin exchange / network instratucture
##
##########################################

    napkin-exchange-proxy:

        container_name: napkin-exchange-proxy

        image: nginxproxy/nginx-proxy

        restart: unless-stopped

        ports:

            - 80:80

            - 443:443

        volumes:

            - /var/run/docker.sock:/tmp/docker.sock:ro

            - /var/docker/nginx/html:/usr/share/nginx/html

            - /var/docker/nginx/certs:/etc/nginx/certs

            - /var/docker/nginx/vhost:/etc/nginx/vhost.d

        logging:

            options:

                max-size: "10m"

                max-file: "3"

    napkin-exchange-letsencrypt:

        container_name: napkin-exchange-letsencrypt

        image: jrcs/letsencrypt-nginx-proxy-companion

        restart: unless-stopped

        volumes_from:

            - napkin-exchange-proxy

        volumes:

            - /var/run/docker.sock:/var/run/docker.sock

            - /var/docker/nginx/acme:/etc/acme.sh

        environment:

            DEFAULT_EMAIL: troy@softwareshinobi.com
            
##########################################
##
## Relational Data / Postgres / Server
##
##########################################

    postgres-database-server:

        container_name: postgres-database-server
        
        image: postgres:14.1-alpine

        restart: unless-stopped

        ports:

            - "5432:5432"

        volumes: 

            - /volumes/embanet/postgres/database:/var/lib/postgresql/data

        environment: 

            - POSTGRES_DB=shinobi

            - POSTGRES_USER=shinobi

            - POSTGRES_PASSWORD=shinobi

##########################################
##
## Relational Data / Postgres / Dashboard
##
##########################################

    postgres.monterrey.embanet.online:

        container_name: postgres.monterrey.embanet.online

        image: dpage/pgadmin4
        
        user: "5050:5050"

        restart: unless-stopped

        depends_on:

            - postgres-database-server
        
        ports:
        
            - "5480:80"
            
        volumes:

            - /tmp/sandbox/volumes/embanet/postgres/admin:/var/lib/pgadmin      

        environment:
        
            PGADMIN_DEFAULT_EMAIL: user@loremipsum.com
            
            PGADMIN_DEFAULT_PASSWORD: shinobi

            VIRTUAL_HOST: postgres.monterrey.embanet.online

            LETSENCRYPT_HOST: postgres.monterrey.embanet.online
